### ISSUE TITLE
Status code 413 on file upload (12mb)

### ISSUE THREAD

**Issue by tmdoit-zz** [node-red-contrib-utils/node-red-contrib-browser-utils#14]
When trying to upload file which has size 12mb, I've get 413 code. Request size is untouched (50mb) in source code.
I've get response after three minutes, exact time which takes to upload it manually.

**Comment by chughts** [comment]
A 413 code indicates that the request entity is too large. The file upload, camera and microphone nodes in this package encode the file / picture / audio and send that as part of a GET request. It was built when there was no http post multi-part option available in node-red. 

Now that there is a multi-part post capability in the http in node, I think you should consider using that for large files.

**Comment by tmdoit-zz** [comment]
Great, thanks for your time!
