### ISSUE TITLE
camera.onclick TypeError: Cannot read property 'getUserMedia' of undefined

### ISSUE THREAD

**Issue by ptitzler** [node-red-contrib-utils/node-red-contrib-browser-utils#19]
Node-RED: 0.20.7
node-red-contrib-browser-utils: 0.0.9
Browser: Chrome 76.0.38...

Triggering the camera node in a basic flow the following error is displayed in the browser's console:

```
Definition error: camera.onclick TypeError: Cannot read property 'getUserMedia' of undefined
    at takeSnapshot (eval at <anonymous> (vendor.js:2), <anonymous>:75:34)
    at Object.onclick (eval at <anonymous> (vendor.js:2), <anonymous>:111:21)
    at SVGRectElement.Ie (red.min.js:16)
    at SVGRectElement.i [as __onclick] (vendor.js:32)
```

I am running Node-RED in a Docker image. The camera node works just fine if I run the Docker image locally. However, if I deploy the same Docker image on Red Hat OpenShift, above error is raised for the same flow and the same browser. No errors are displayed in the Node-RED log. 

Based on what is stated here https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Security, one reason could be that " [...] you try to call getUserMedia() in an insecure context, since navigator.mediaDevices is undefined in an insecure context.". 

Do I need to configure a secured connection for this to work remotely?

**Comment by chughts** [comment]
Unless accessible through a localhost port, the camera / microphone nodes need https to be enabled on the page.

**Comment by ptitzler** [comment]
Alright. Thanks for confirming!
