### ISSUE TITLE
Add input to microphone node

### ISSUE THREAD

**Issue by johnwalicki** [node-red-contrib-utils/node-red-contrib-browser-utils#20]
I would like to send an input 'start' / 'stop' message to the microphone node.  That would allow me to wire the microphone node into a Node-RED dashboard instead of clicking the microphone node tab.

I looked at adding this capability myself. Inside microphone.html, I have changed
```inputs:1,```
and inside microphone.js I added 
```
    this.on('input', function (msg) {
      if(msg.payload == 'start') {
            getRecorder(this.id)
      } else if (msg.payload == 'stop' ) {
            stopRecording(this.id, uploadRecord)
      }
    })
```
But the microphone node has an unconventional split of the javascript between the html and js files.
The above fails on an inject of a string 'start' because getRecorder() is not available to the microphone.js because its defined in the microphone.html

**Comment by chughts** [comment]
The split is because the node uses the browser context to access the microphone. This requires explicit user action as well as user authorisation for the node to access the microphone. 

I will, however, take a look at the code to see what can be done. I may initially create a new node with an input, and a heartbeat to determine when a start or end event occurs.

**Comment by johnwalicki** [comment]
Even if the node was restructured, while the user was on the Node-RED Dashboard, does the microphone need access to the browser context of Node-RED Dashboard tab or the Node-RED editor tab?
I asked Nick some questions.  He was going to ask Dave CJ.
This is an important use case.  Recording from the Node-RED Dashboard would be very useful.

**Comment by johnwalicki** [comment]
Nick did some great work on node-red-node-ui-microphone so you can now have a Node-RED Dashboard that records speech.  It's straightforward to wire the new microphone node to the Watson Speech to Text node.
https://flows.nodered.org/node/node-red-node-ui-microphone

**Comment by johnwalicki** [comment]
Closing issue.
