### ISSUE TITLE
Send filename with fileinject

### ISSUE THREAD

**Issue by skadefro** [node-red-contrib-utils/node-red-contrib-browser-utils#23]
Would it be possible to add support for getting filename of the file uploaded ?
Could be as msg.filename and maybe even add msg.mimetype too

**Comment by chughts** [comment]
If someone is able to add this feature then I will be happy to accept a pull request.

**Comment by raghavgurbaxani** [comment]
has this been resolved ? any solution to this ?

**Comment by skadefro** [comment]
Is there any ETA on when the PR will be published ?
Both [npm](https://www.npmjs.com/package/node-red-contrib-browser-utils) and the [nodered repo](https://flows.nodered.org/node/node-red-contrib-browser-utils) is reporting latest version to be 0.0.9 from 1 year, 11 months ago

**Comment by chughts** [comment]
just published.

**Comment by skadefro** [comment]
your still missing the [flows site](https://flows.nodered.org/node/node-red-contrib-browser-utils) ( its no longer automatic )

**Comment by skadefro** [comment]
oh, apparently i can also check for updates on the site, after logging in, so it is updated now.
