### ISSUE TITLE
"Stream was 44 bytes but needs to be at least 100 bytes" when used with Watson Speech to Text

### ISSUE THREAD

**Issue by petertuton** [node-red-contrib-utils/node-red-contrib-browser-utils#7]
When using the microphone node and passing the output to the Watson Speech to Text (STT) node, STT returns the error, "Stream was 44 bytes but needs to be at least 100 bytes".

**Comment by chughts** [comment]
Please post a sample flow here.

**Comment by petertuton** [comment]
Sample flow provided. Note that I've removed the Watson Speech to Text (STT) credentials, otherwise it's a simple flow with just the microphone node, STT node and debug node.

```
[
    {
        "id": "a7ebc76b.ab426",
        "type": "tab",
        "label": "Flow 1"
    },
    {
        "id": "32f0fc42.bc5544",
        "type": "microphone",
        "z": "a7ebc76b.ab426",
        "name": "",
        "x": 105.5,
        "y": 121,
        "wires": [
            [
                "69f114d3.76c91c"
            ]
        ]
    },
    {
        "id": "d588c3e9.843e48",
        "type": "debug",
        "z": "a7ebc76b.ab426",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 531.5,
        "y": 121,
        "wires": []
    },
    {
        "id": "69f114d3.76c91c",
        "type": "watson-speech-to-text",
        "z": "a7ebc76b.ab426",
        "name": "",
        "alternatives": 1,
        "speakerlabels": true,
        "smartformatting": false,
        "lang": "en-US",
        "langhidden": "en-US",
        "langcustom": "NoCustomisationSetting",
        "langcustomhidden": "",
        "band": "NarrowbandModel",
        "bandhidden": "",
        "password": "",
        "payload-response": true,
        "default-endpoint": true,
        "service-endpoint": "https://stream.watsonplatform.net/speech-to-text/api",
        "x": 313.5,
        "y": 121,
        "wires": [
            [
                "d588c3e9.843e48"
            ]
        ]
    }
]
```

**Comment by smchamberlin** [comment]
Hi ptuton,

I tried your flow and it worked for me, I recorded a movie of it:

https://github.com/ibm-early-programs/node-red-contrib-browser-utils/blob/smchamberlin-screenshot-video/Screen%20Recording.mov

When was the last time you pulled down the latest codes?  Are you on the Bluemix version of Node-RED or local?  Either way, might be good to start fresh and try again, get the latest Node-RED, latest STT node, microphone node, etc.

I was able to demonstrate that it's not broken so we just need to figure out why it's not working for you.  If you can you might also try creating a fresh STT service.

Steve

P.S. I'm using a Node-RED that I created using the Bluemix boilerplate a few weeks ago.

**Comment by petertuton** [comment]
Hi Steve,

I'm using Safari. Confirming it works in Chrome. Perhaps the README includes a note about browser support? 

Thanks for the quick turn-around. 

Regards,
Peter.

**Comment by smchamberlin** [comment]
Peter, oh weird - when I try it on Safari, I get this error message; you don't see that ?  I'm on Safari 10.1.1 on Mac Sierra.

![node-red_microphone](https://user-images.githubusercontent.com/10179723/34592848-db2ba73c-f17b-11e7-820d-00eccf6c5638.png)

**Comment by petertuton** [comment]
Yes, weird... and a little more so because I'm seeing inconsistent behaviour now. 

The flow I supplied earlier was created today (on IBM Cloud using the Node-RED boilerplate, FYI) to ensure nothing had changed since creating the issue. When I tired it on Safari, before responding to you, I experienced the 44 bytes error. However, now after using Chrome and trying it again on Safari  the result is an empty string, i.e. there is no error but there is also no output ("").

I'm using Safari 11.0.2 on macOS 10.13.2.

**Comment by smchamberlin** [comment]
Hi Peter,

I'm glad you got it working with Chrome.

I looked into it a little more, and I think you uncovered a bug that has surfaced now that Safari has added support for something that we were previously using in the code as a safeguard check against Safari:

Consider the line of code here:

https://github.com/ibm-early-programs/node-red-contrib-browser-utils/blob/master/microphone/microphone.html#L79

       function getRecorder(id) {
            if(!navigator.getUserMedia) {
                window.alert('Your browser does not support audio recording')
                return
            }

From this link:

https://caniuse.com/#feat=stream

I can see that support for getUserMedia/Stream API was added in Safari 11.  So that line of code is passing now when it would previously return the error message, but then you're running into some other problem with Safari.  Sounds like we need to revisit whether microphone can work with Safari and if still not, we need to change the code that checks for browser compatibility.

**Comment by chughts** [comment]
Just tried it on Safari 11.0.2, and once you allow Safari to access your microphone then the flow works.

<img width="552" alt="screen shot 2018-01-11 at 11 33 28" src="https://user-images.githubusercontent.com/10371360/34823710-877ef920-f6c3-11e7-955d-8853c90e8100.png">


[{"id":"3becb8be.49fa08","type":"microphone","z":"e5a9c707.e64d68","name":"","x":126,"y":118,"wires":[["e44758c.b5916a8"]]},{"id":"e44758c.b5916a8","type":"watson-speech-to-text","z":"e5a9c707.e64d68","name":"","alternatives":1,"speakerlabels":false,"smartformatting":false,"lang":"en-US","langhidden":"en-US","langcustom":"NoCustomisationSetting","langcustomhidden":"NoCustomisationSetting","band":"BroadbandModel","bandhidden":"BroadbandModel","password":"","payload-response":true,"default-endpoint":true,"service-endpoint":"https://stream.watsonplatform.net/speech-to-text/api","x":342,"y":154,"wires":[["2057e71c.d8cfd8"]]},{"id":"2057e71c.d8cfd8","type":"debug","z":"e5a9c707.e64d68","name":"","active":true,"console":"false","complete":"false","x":534,"y":121,"wires":[]}]
